name: Validation

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  json-validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "24.x"

      - id: npm_install
        run: npm run setup

      - name: SLSA
        uses: ministryofjustice/devsecops-actions/sca/slsa@7dc13c20e2bf541b8a77fa1320a04983b18846f6

      - id: lint
        run: npm run format

      - name: Replace ref in main schema for validation
        run: sed -i "s/main/$(git rev-parse HEAD | tr -d '[:space:]')/g" schema/2.0.0/data-product-definition-schema.json

      - name: Replace ref in test-dpd for validation
        run: sed -i "s/main/$(git rev-parse HEAD | tr -d '[:space:]')/g" schema/2.0.0/test-dpd.json

      - name: Validate all the DPDs against the JSON schema
        id: validate-json
        run: npm run validate
